name: github
baseurl: /github
description: Github Integration for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.3+3-9bd576cd-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
