name: github
baseurl: /github
description: Github Integration for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.10+19-dc6f71ab-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
