name: github
baseurl: /github
description: Github Integration for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.8+11-97daf236-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
