name: github
baseurl: /github
description: Github Integration for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.9+13-62e869aa-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
