name: github
baseurl: /github
description: Github Integration for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.6+2-7e5c9730-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
