name: github
baseurl: /github
description: Github Integration for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.10+5-9c3ad026-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
