name: github
baseurl: /github
description: Github Integration for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.2+1-2ad87e5c-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
