name: github
baseurl: /github
description: Github Integration for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.4+21-b13b9ea5-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
