name: github
baseurl: /github
description: Github Integration for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.3+5-41b847c8-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
