name: github
baseurl: /github
description: Github Integration for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.1+1-035fc0b3-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
