name: github
baseurl: /github
description: Github Integration for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.7+7-57716a1c-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
